server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:local;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# 로컬 로그 확인용
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace